language: cpp

compiler:
  - clang

addons:
  apt:
    packages:
    - cmake
    - librdf0-dev
    - libboost-filesystem-dev
    - libboost-date-time-dev

# Run the Build script
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install && cmake --build . --target install
  - ./tests/gtest-all
